"""Main circuit drawer interface for squin circuits."""

from __future__ import annotations

import logging
from typing import Any

from kirin import ir

from bloqade.squin import kernel

from . import text as _text
from . import matplotlib as _matplotlib
from .utils import get_layered_instructions

logger = logging.getLogger(__name__)


def circuit_drawer(
    circuit: ir.Method,
    scale: float | None = None,
    filename: str | None = None,
    style: dict | str | None = None,
    output: str | None = None,
    interactive: bool = False,
    plot_barriers: bool = True,
    reverse_bits: bool = False,
    justify: str | None = None,
    vertical_compression: str | None = "medium",
    idle_wires: bool = True,
    fold: int | None = None,
    ax: Any | None = None,
    initial_state: bool = False,
) -> Any:
    """Draw a squin circuit.

    Args:
        circuit: The squin kernel method to visualize.
        scale: Scale of image to draw (shrink if < 1.0). Only used by
            the `mpl` output. Defaults to 1.0.
        filename: File path to save image to. Defaults to None (result not saved in a file).
        style: Style name or dictionary specifying the style. Only used by `mpl` output.
        output: Select the output method to use for drawing the circuit.
            Valid choices are `text`, `mpl`. By default, the `text` drawer is used.
        interactive: When set to True, show the circuit in a new window
            (for `mpl` this depends on the matplotlib backend being used
            supporting this). Note when used with the `text` output type this has no effect.
            Defaults to False.
        plot_barriers: Enable/disable drawing barriers in the output
            circuit. Defaults to True.
        reverse_bits: When set to True, reverse the bit order inside
            registers for the output visualization. Defaults to False.
        justify: Options are "left", "right" or "none" (str).
            If anything else is supplied, left justified will be used instead.
            It refers to where gates should be placed in the output circuit if
            there is an option. "none" results in each gate being placed in
            its own column. Defaults to "left".
        vertical_compression: "high", "medium" or "low". It
            merges the lines generated by the `text` output so the drawing
            will take less vertical room. Default is "medium". Only used by
            the `text` output, will be silently ignored otherwise.
        idle_wires: Include (or not) idle wires (wires with no circuit elements)
            in output visualization. Default is True.
        fold: Sets pagination. In `text`, sets the length of the lines.
            This is useful when the drawing does not fit in the console.
            If None (default), it will try to guess the console width using
            `shutil.get_terminal_size()`. However, if running in jupyter,
            the default line length is set to 80 characters.
            In `mpl`, it is the number of (visual) layers before folding.
            Default is 25.
        ax: Only used by the `mpl` backend. An optional matplotlib.axes.Axes
            object to be used for the visualization output. If none is
            specified, a new matplotlib Figure will be created and used.
            Additionally, if specified there will be no returned Figure since
            it is redundant.
        initial_state: Adds |0⟩ in the beginning of the qubit wires.
            Default is False.

    Returns:
        TextDrawing (if output='text'): A drawing that can be printed as ascii art.
        matplotlib.figure.Figure (if output='mpl'): A matplotlib figure object for the circuit diagram.

    Raises:
        ValueError: when an invalid output method is selected
        ImportError: when the output methods requires non-installed libraries.

    Example:
        .. code-block:: python

            from bloqade import squin
            from bloqade.visual.circuit import circuit_drawer

            @squin.kernel
            def main():
                q = squin.qalloc(2)
                squin.h(q[0])
                squin.cx(q[0], q[1])

            circuit_drawer(main, output="text")
    """
    if output is None:
        output = "text"

    if output == "text":
        return _text_circuit_drawer(
            circuit,
            filename=filename,
            reverse_bits=reverse_bits,
            plot_barriers=plot_barriers,
            justify=justify,
            vertical_compression=vertical_compression,
            idle_wires=idle_wires,
            fold=fold,
            initial_state=initial_state,
        )
    elif output == "mpl":
        image = _matplotlib_circuit_drawer(
            circuit,
            scale=scale,
            filename=filename,
            style=style,
            plot_barriers=plot_barriers,
            reverse_bits=reverse_bits,
            justify=justify,
            idle_wires=idle_wires,
            fold=fold,
            ax=ax,
            initial_state=initial_state,
        )
        if image and interactive:
            image.show()
        return image
    else:
        raise ValueError(
            f"Invalid output type {output} selected. The only valid choices "
            "are text and mpl"
        )


def _text_circuit_drawer(
    circuit: ir.Method,
    filename: str | None = None,
    reverse_bits: bool = False,
    plot_barriers: bool = True,
    justify: str | None = None,
    vertical_compression: str | None = "medium",
    idle_wires: bool = True,
    fold: int | None = None,
    initial_state: bool = False,
):
    """Draws a circuit using ascii art.

    Args:
        circuit: Input squin kernel method
        filename: Optional filename to write the result
        reverse_bits: Rearrange the bits in reverse order.
        plot_barriers: Draws the barriers when they are there.
        justify: `left`, `right` or `none`. Defaults to `left`. Says how
            the circuit should be justified.
        vertical_compression: `high`, `medium`, or `low`. It merges the
            lines so the drawing will take less vertical room. Default is `medium`.
        idle_wires: Include idle wires. Default is True.
        fold: Optional. Breaks the circuit drawing to this length. This
            is useful when the drawing does not fit in the console. If
            None (default), it will try to guess the console width using
            `shutil.get_terminal_size()`. If you don't want pagination
            at all, set `fold=-1`.
        initial_state: Optional. Adds |0⟩ in the beginning of the line.
            Default: False.

    Returns:
        TextDrawing: An instance that, when printed, draws the circuit in ascii art.

    Raises:
        ValueError: When the filename extension is not .txt.
    """
    qubits, nodes = get_layered_instructions(
        circuit,
        reverse_bits=reverse_bits,
        justify=justify,
        idle_wires=idle_wires,
    )
    text_drawing = _text.TextDrawing(
        qubits,
        nodes,
        circuit,
        reverse_bits=reverse_bits,
        initial_state=initial_state,
    )
    text_drawing.plotbarriers = plot_barriers
    text_drawing.line_length = fold
    text_drawing.vertical_compression = vertical_compression

    if filename:
        text_drawing.dump(filename)
    return text_drawing


def _matplotlib_circuit_drawer(
    circuit: ir.Method,
    scale: float | None = None,
    filename: str | None = None,
    style: dict | str | None = None,
    plot_barriers: bool = True,
    reverse_bits: bool = False,
    justify: str | None = None,
    idle_wires: bool = True,
    fold: int | None = None,
    ax: Any | None = None,
    initial_state: bool = False,
    interactive: bool = False,
):
    """Draw a quantum circuit based on matplotlib.

    Args:
        circuit: A squin kernel method
        scale: Scaling factor
        filename: File path to save image to
        style: Dictionary of style or file name of style file
        reverse_bits: When set to True, reverse the bit order inside
            registers for the output visualization.
        plot_barriers: Enable/disable drawing barriers in the output
            circuit. Defaults to True.
        justify: `left`, `right` or `none`. Defaults to `left`. Says how
            the circuit should be placed.
        idle_wires: Include idle wires. Default is True.
        fold: Number of vertical layers allowed before folding. Default is 25.
        ax: An optional Axes object to be used for the visualization output.
            If none is specified, a new matplotlib Figure will be created and used.
        initial_state: Optional. Adds |0⟩ in the beginning of the line.
            Default: False.

    Returns:
        matplotlib.figure: A matplotlib figure object for the circuit diagram
            if the `ax` kwarg is not set.
    """
    qubits, nodes = get_layered_instructions(
        circuit,
        reverse_bits=reverse_bits,
        justify=justify,
        idle_wires=idle_wires,
    )
    if fold is None:
        fold = 25

    qcd = _matplotlib.MatplotlibDrawer(
        qubits,
        nodes,
        circuit,
        scale=scale,
        style=style,
        reverse_bits=reverse_bits,
        plot_barriers=plot_barriers,
        fold=fold,
        ax=ax,
        initial_state=initial_state,
    )
    fig = qcd.draw(filename)
    
    # If interactive, show the plot
    if interactive and fig is not None:
        import matplotlib.pyplot as plt
        # Use block=True to keep window open until user manually closes it
        # This blocks execution until the window is closed
        plt.show(block=True)
    
    return fig
